### ISSUE TITLE
大神,问个问题

### ISSUE THREAD

**Issue by Gardelll** [littlepinecone/tieba_robot#1]
贴吧根据Cookie获得的tbs失效的时间是多少，为什么我用多久之前的tbs发帖依然成功呢

**Comment by seishinkouki** [comment]
失效具体也不清楚,有时候我机器人挂了几天在登录有效的情况下不能回帖,提示操作频繁

**Comment by littlepinecone** [comment]
失效具体也不清楚,有时候我机器人挂了几天在登录有效的情况下不能回帖,提示操作频繁

**Comment by SunXinao** [comment]
提示操作频繁的时候只是回帖间隔太近，调大就没问题，我觉得理论上tbs有效期和使用的BDUSS一样，在百度贴吧的sqlite数据库里BDUSS和tbs放在同一个表里，而且很长时间不变
